# Generated by Django 3.0.5 on 2020-05-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200509_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='you@eknm.net', max_length=32),
            preserve_default=False,
        ),
    ]
